import os
import json
import sys
from dotenv import load_dotenv
import anthropic

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE

load_dotenv()
client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
MODEL = "claude-sonnet-4-6"

TEAL = RGBColor(0, 102, 153)
DARK_BLUE = RGBColor(0, 51, 102)
WHITE = RGBColor(255, 255, 255)
OFF_WHITE = RGBColor(250, 250, 250)


def create_powerpoint(insights_text: str, output_file: str = "dataset_insights.pptx") -> dict:
    """
    Creates a .pptx from insights_text.
    Sections delimited by '###' become individual content slides.
    Returns a dict with keys: success, output_file, slide_count, error.
    """
    try:
        prs = Presentation()
        prs.slide_width = Inches(10)
        prs.slide_height = Inches(7.5)

        def apply_brand(slide):
            slide.background.fill.solid()
            slide.background.fill.fore_color.rgb = OFF_WHITE
            banner = slide.shapes.add_shape(
                MSO_SHAPE.RECTANGLE,
                Inches(0), Inches(0), prs.slide_width, Inches(0.6),
            )
            banner.fill.solid()
            banner.fill.fore_color.rgb = TEAL
            try:
                banner.line.fill.background()
            except Exception:
                pass
            tf = banner.text_frame
            tf.text = "Dataset Insights"
            p = tf.paragraphs[0]
            p.alignment = PP_ALIGN.CENTER
            p.font.size = Pt(16)
            p.font.bold = True
            p.font.color.rgb = WHITE

        # Title slide
        title_slide = prs.slides.add_slide(prs.slide_layouts[0])
        title_slide.shapes.title.text = "Dataset Analysis Insights"
        title_slide.placeholders[1].text = "Generated by AI Analysis"
        apply_brand(title_slide)

        # Parse sections delimited by ###
        lines = insights_text.splitlines()
        buffer = []
        current_title = None

        def flush_slide(title_text, items):
            if not items and not title_text:
                return
            slide = prs.slides.add_slide(prs.slide_layouts[5])
            apply_brand(slide)

            title_box = slide.shapes.add_textbox(
                Inches(0.5), Inches(0.8), Inches(9), Inches(0.7)
            )
            tf = title_box.text_frame
            tf.clear()
            tf.text = title_text or "Details"
            tf.paragraphs[0].font.size = Pt(28)
            tf.paragraphs[0].font.bold = True
            tf.paragraphs[0].font.color.rgb = DARK_BLUE

            content_box = slide.shapes.add_textbox(
                Inches(0.5), Inches(1.6), Inches(9), Inches(5)
            )
            cf = content_box.text_frame
            cf.word_wrap = True
            cf.clear()
            for item in items:
                par = cf.add_paragraph()
                par.text = item
                par.font.size = Pt(16)

        for line in lines:
            stripped = line.strip()
            if not stripped:
                continue
            if stripped.startswith("###"):
                flush_slide(current_title, buffer)
                buffer = []
                current_title = stripped.lstrip("#").strip()
            else:
                buffer.append(stripped)

        flush_slide(current_title, buffer)

        prs.save(output_file)
        return {"success": True, "output_file": output_file, "slide_count": len(prs.slides)}

    except Exception as e:
        return {"success": False, "error": str(e)}


TOOL_REGISTRY = {
    "create_powerpoint": create_powerpoint,
}

TOOLS = [
    {
        "name": "create_powerpoint",
        "description": (
            "Generates a PowerPoint (.pptx) presentation file from structured insights text. "
            "The insights_text MUST use '###' as the section delimiter for slide titles "
            "(e.g., '### 1. Summary Statistics'). Each ### section becomes one content slide. "
            "Returns JSON with keys: success (bool), output_file (str), slide_count (int), "
            "and error (str, only on failure)."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "insights_text": {
                    "type": "string",
                    "description": (
                        "The full insights text structured with '###' heading markers to denote "
                        "slide boundaries. Example:\n"
                        "### 1. Summary Statistics\n- Key point one\n- Key point two\n\n"
                        "### 2. Key Trends\n- Trend one\n"
                    ),
                },
                "output_file": {
                    "type": "string",
                    "description": "Filename for the output .pptx file, including the .pptx extension.",
                },
            },
            "required": ["insights_text", "output_file"],
        },
    }
]

SYSTEM_PROMPT = """You are a PowerPoint presentation specialist. Your sole task is to convert
pre-generated data insights text into a well-structured PowerPoint presentation.

When given insights text, you MUST:
1. Ensure each major section has a '###' heading delimiter (e.g., '### 1. Summary Statistics').
   If the text already uses '###' headings, preserve them exactly. If it uses numbered headings
   without '###', add '###' before each section title.
2. Retain all bullet points, numbered lists, and paragraphs verbatim under each heading.
3. Call the create_powerpoint tool exactly once with the structured insights_text.

Do not include any commentary before or after the tool call."""


def run_pptx_agent(insights_text: str, output_file: str = "dataset_insights.pptx") -> str:
    """
    Runs the Claude tool-use agent loop.
    Returns the path to the generated .pptx file.
    """
    messages = [
        {
            "role": "user",
            "content": (
                f"Please create a PowerPoint presentation from the following insights. "
                f"Save the output as '{output_file}'.\n\n"
                f"--- INSIGHTS ---\n{insights_text}\n--- END INSIGHTS ---"
            ),
        }
    ]

    for _ in range(5):
        response = client.messages.create(
            model=MODEL,
            max_tokens=8192,
            system=SYSTEM_PROMPT,
            tools=TOOLS,
            messages=messages,
        )

        messages.append({"role": "assistant", "content": response.content})

        if response.stop_reason == "end_turn":
            break

        if response.stop_reason == "tool_use":
            tool_results = []
            for block in response.content:
                if block.type != "tool_use":
                    continue
                tool_name = block.name
                tool_input = block.input
                print(f"[Agent] Calling tool: {tool_name} → {tool_input.get('output_file', output_file)}")

                if tool_name not in TOOL_REGISTRY:
                    result = {"success": False, "error": f"Unknown tool: {tool_name}"}
                else:
                    result = TOOL_REGISTRY[tool_name](**tool_input)
                    if result.get("success"):
                        print(f"[Agent] Created: {result['output_file']} ({result['slide_count']} slides)")

                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": block.id,
                    "content": json.dumps(result),
                })

            messages.append({"role": "user", "content": tool_results})

    # Find the output file path from the tool results in history
    for msg in reversed(messages):
        if msg["role"] == "user" and isinstance(msg["content"], list):
            for block in msg["content"]:
                if block.get("type") == "tool_result":
                    result = json.loads(block["content"])
                    if result.get("success"):
                        return result["output_file"]

    raise RuntimeError("Agent completed but no PowerPoint file was created.")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python pptx_agent.py <insights_file.txt> [output.pptx]")
        print("       or pipe via stdin: cat insights.txt | python pptx_agent.py -")
        sys.exit(1)

    input_arg = sys.argv[1]
    output_arg = sys.argv[2] if len(sys.argv) > 2 else "dataset_insights.pptx"

    if input_arg == "-":
        insights = sys.stdin.read()
    else:
        with open(input_arg, "r", encoding="utf-8") as f:
            insights = f.read()

    output_path = run_pptx_agent(insights, output_file=output_arg)
    print(f"Done. Presentation saved to: {output_path}")
