from langchain_community.tools import WikipediaQueryRun, DuckDuckGoSearchRun
from langchain_community.utilities import WikipediaAPIWrapper
from langchain_core.tools import Tool
from datetime import datetime

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE

TEAL = RGBColor(0, 102, 153)
DARK_BLUE = RGBColor(0, 51, 102)
WHITE = RGBColor(255, 255, 255)
OFF_WHITE = RGBColor(250, 250, 250)


### Custom Tool Definitions ###

def save_to_txt(data: str, filename: str = "research_output.txt"):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    formatted_text = f"--- Research Output ---\nTimestamp: {timestamp}\n\n{data}\n\n"

    with open(filename, "a", encoding="utf-8") as f:
        f.write(formatted_text)
    
    return f"Data successfully saved to {filename}"


def create_powerpoint(insights_text: str, output_file: str = "dataset_insights.pptx") -> dict:
    """
    Creates a .pptx from insights_text.
    Sections delimited by '###' become individual content slides.
    Returns a dict with keys: success, output_file, slide_count, error.
    """
    try:
        prs = Presentation()
        prs.slide_width = Inches(10)
        prs.slide_height = Inches(7.5)

        def apply_brand(slide):
            slide.background.fill.solid()
            slide.background.fill.fore_color.rgb = OFF_WHITE
            banner = slide.shapes.add_shape(
                MSO_SHAPE.RECTANGLE,
                Inches(0), Inches(0), prs.slide_width, Inches(0.6),
            )
            banner.fill.solid()
            banner.fill.fore_color.rgb = TEAL
            try:
                banner.line.fill.background()
            except Exception:
                pass
            tf = banner.text_frame
            tf.text = "Dataset Insights"
            p = tf.paragraphs[0]
            p.alignment = PP_ALIGN.CENTER
            p.font.size = Pt(16)
            p.font.bold = True
            p.font.color.rgb = WHITE

        # Title slide
        title_slide = prs.slides.add_slide(prs.slide_layouts[0])
        title_slide.shapes.title.text = "Dataset Analysis Insights"
        title_slide.placeholders[1].text = "Generated by AI Analysis"
        apply_brand(title_slide)

        # Parse sections delimited by ###
        lines = insights_text.splitlines()
        buffer = []
        current_title = None

        def flush_slide(title_text, items):
            if not items and not title_text:
                return
            slide = prs.slides.add_slide(prs.slide_layouts[5])
            apply_brand(slide)

            title_box = slide.shapes.add_textbox(
                Inches(0.5), Inches(0.8), Inches(9), Inches(0.7)
            )
            tf = title_box.text_frame
            tf.clear()
            tf.text = title_text or "Details"
            tf.paragraphs[0].font.size = Pt(28)
            tf.paragraphs[0].font.bold = True
            tf.paragraphs[0].font.color.rgb = DARK_BLUE

            content_box = slide.shapes.add_textbox(
                Inches(0.5), Inches(1.6), Inches(9), Inches(5)
            )
            cf = content_box.text_frame
            cf.word_wrap = True
            cf.clear()
            for item in items:
                par = cf.add_paragraph()
                par.text = item
                par.font.size = Pt(16)

        for line in lines:
            stripped = line.strip()
            if not stripped:
                continue
            if stripped.startswith("###"):
                flush_slide(current_title, buffer)
                buffer = []
                current_title = stripped.lstrip("#").strip()
            else:
                buffer.append(stripped)

        flush_slide(current_title, buffer)

        prs.save(output_file)
        return {"success": True, "output_file": output_file, "slide_count": len(prs.slides)}

    except Exception as e:
        return {"success": False, "error": str(e)}


### Tool Instances ###

save_tool = Tool(
    name="save_text_to_file",
    func=save_to_txt,
    description="Saves structured research data to a text file.",
)

search = DuckDuckGoSearchRun()
search_tool = Tool(
    name="search",
    func=lambda q: search.run(q),
    description="Search the web for information. Input should be a search query string.",
)

api_wrapper = WikipediaAPIWrapper(top_k_results=1, doc_content_chars_max=100)
wiki = WikipediaQueryRun(api_wrapper=api_wrapper)
wiki_tool = Tool(
    name="wikipedia",
    func=lambda q: wiki.run(q),
    description="Search Wikipedia for information. Input should be a search query string.",
)


create_powerpoint_tool = Tool(
    name="create_powerpoint",
    func=create_powerpoint,
    description=(
        "Generates a PowerPoint (.pptx) presentation file from structured insights text. "
        "Sections in the input text delimited by '###' will become individual slides with the section title as the slide title and the content as bullet points."
    ),
)
